import type { ManualService,Operation,RequestOptions,Result } from '../manual/service'
import {schemas} from '../manual/contract.generated'
import {matches} from '../manual/validation'
import { ManualError } from '../manual/service'
import type { Operations,ManualInterviewSession,ManualIntentReview,ManualInterviewAnswer,ManualInterviewCorrection,ManualInterviewPhotoUpdate,ManualDraft,ManualDraftCorrection,ManualDraftCorrectionInput,ManualIssueAcknowledgement,ManualPublishInput } from '../manual/types'
import {draftFixture} from './manualDraftFixtures'
import {publicationInput} from '../manual/draftCommands'
import { interviewFixture,manualStoreId,stateFixture,reviewFixture } from './manualFixtures'
export function createManualPreviewService(resume=false,scenario=''):ManualService {
 const asSession=(value:unknown):ManualInterviewSession=>{if(!matches(schemas.ManualInterviewSession,value,schemas))throw new ManualError('INVALID_PREVIEW_SESSION');return value as ManualInterviewSession}
 let session:ManualInterviewSession=structuredClone(interviewFixture)
 let started=resume||!!scenario,count=0,sequence=0
 const media=new Map<string,Blob>()
 const reviews=new Map<string,ManualIntentReview>(),results=new Map<string,unknown>(),transcriptions=new Map<string,string>(),turns:Operations['getManualInterviewTurns']['output']['items']=[]
 const asDraft=(value:unknown):ManualDraft=>{if(!matches(schemas.ManualDraft,value,schemas))throw new ManualError('INVALID_PREVIEW_DRAFT');return value as ManualDraft}
 const asJob=(value:unknown):ManualDraftCorrection=>{if(!matches(schemas.ManualDraftCorrection,value,schemas))throw new ManualError('INVALID_PREVIEW_JOB');return value as ManualDraftCorrection}
 let draft:ManualDraft=asDraft({...draftFixture,generationStatus:'NOT_STARTED',content:null,latestCorrection:null}),publishedId:string|null=null
 const stages=['WORK_STRUCTURE','COMMON_TASKS','SHIFT_TASKS','COMPLEMENTS'] as const
 session.intents=stages.map((stage,i)=>({...session.intents[0],id:i===0?session.intents[0].id:crypto.randomUUID(),stage,key:['근무조와 시간','공통 업무','근무별 업무','규정·설비'][i],depth:0,coverage:'PENDING',finishedAt:null}))
 function makeReview(intentId:string){const stage=session.intents.find(i=>i.id===intentId)?.stage;return {...structuredClone(reviewFixture),intentId,content:{...structuredClone(reviewFixture.content!),intentId,sections:stage==='WORK_STRUCTURE'?[]:[{...structuredClone(draftFixture.content.sections[0]),id:crypto.randomUUID(),category:stage==='SHIFT_TASKS'?'SHIFT_TASK':stage==='COMPLEMENTS'?'RULE':'COMMON_TASK',shiftId:stage==='SHIFT_TASKS'?draftFixture.content.shifts[0].id:null,title:stage==='COMPLEMENTS'?'화장실 이용':stage==='SHIFT_TASKS'?'입고 물품 확인':'재고 정리'}]}} as ManualIntentReview}
 function finishIntent(index:number){const intent=session.intents[index];if(!intent)return;session.intents[index]={...intent,...(scenario==='depth5'?{coverage:'NEEDS_DETAIL' as const,depth:5 as const,finishedAt:new Date().toISOString()}:{coverage:'COVERED' as const,depth:0,finishedAt:new Date().toISOString()})};reviews.set(intent.id,makeReview(intent.id))}
 if(scenario==='review'||scenario==='review-error'||scenario==='depth5'){finishIntent(0);session=asSession({...session,revision:session.revision+1,currentIntentId:session.intents[1].id,questions:[{...session.questions[0],id:crypto.randomUUID(),intentId:session.intents[1].id,text:'모두가 하는 일은 무엇인가요?'}]});if(scenario==='review-error'){const r=reviews.get(session.intents[0].id)!;reviews.set(r.intentId,{...r,status:'ERROR',confirmedAt:null,error:{code:'AI_PROCESSING_FAILED',message:'요약 실패',retryable:true},processing:{taskId:crypto.randomUUID(),kind:'UNDERSTANDING',attempt:1}})}}
 if(scenario==='ready'||['draft','missing','noop-missing','correction-running','correction-error','correction-clarify','correction-noop','generation-error'].includes(scenario)){session.intents.forEach((_,i)=>finishIntent(i));session=asSession({...session,status:'IN_PROGRESS',phase:'READY_TO_GENERATE',currentIntentId:null,questions:[],processing:null,error:null,completedAt:null})}
 if(['draft','missing','noop-missing','correction-running','correction-error','correction-clarify','correction-noop','generation-error'].includes(scenario)){session=asSession({...session,status:'COMPLETED',phase:'COMPLETED',completedAt:new Date().toISOString()});draft=structuredClone(draftFixture);if(scenario==='missing'||scenario==='noop-missing')draft=asDraft({...draft,content:{...draft.content,shifts:draft.content!.shifts.map(shift=>({...shift,endTime:null})) ,missingInformation:[{id:'eae0fb79-c6cd-40b1-a127-f3e3e93c5f87',target:'SHIFT',targetId:draft.content!.shifts[0].id,field:'endTime',description:'야간조 종료 시간 확인 필요'}]},issues:[{id:'eae0fb79-c6cd-40b1-a127-f3e3e93c5f87',intentId:session.intents[0].id,description:'야간조 종료 시간 확인 필요',status:'OPEN',ownerNote:null,acknowledgedAt:null}]});if(scenario==='generation-error'){session=asSession({...session,status:'ERROR',phase:'ERROR',completedAt:null,processing:{taskId:crypto.randomUUID(),kind:'DRAFT_GENERATION',attempt:1},error:{code:'AI_PROCESSING_FAILED',message:'생성 실패',retryable:true}});draft=asDraft({...draft,generationStatus:'ERROR',content:null})}}
 if(['correction-running','correction-error','correction-clarify'].includes(scenario)){const failed=scenario!=='correction-running';draft=asDraft({...draft,latestCorrection:asJob({id:crypto.randomUUID(),versionId:draft.versionId,baseRevision:draft.revision,target:{kind:'SHIFT',targetId:draft.content!.shifts[0].id},status:failed?'ERROR':'RUNNING',attempt:1,resultRevision:null,error:failed?{code:scenario==='correction-error'?'AI_PROCESSING_FAILED':'CORRECTION_CLARIFICATION_REQUIRED',message:'샘플 정정 실패',retryable:scenario==='correction-error'}:null,createdAt:new Date().toISOString(),completedAt:failed?new Date().toISOString():null})})}
 return {storeId:manualStoreId,async call<N extends Operation>(name:N,params:Record<string,string>,input:Operations[N]['input'],options:RequestOptions):Promise<Result<Operations[N]['output']>>{
  options.signal.throwIfAborted()
  if(options.key&&results.has(options.key))return {data:structuredClone(results.get(options.key)) as Operations[N]['output'],retryAfterMs:2000}
  let data:unknown
  switch(name){
   case 'getOwnerManualState':data={...stateFixture,currentPublishedVersionId:publishedId,interviewSessionId:publishedId?null:started?session.id:null,draftVersionId:publishedId?null:started?session.draftVersionId:null};break
   case 'getManualDraft':{if(publishedId)throw new ManualError('MANUAL_RESOURCE_NOT_FOUND');if(draft.generationStatus==='RUNNING'){draft=asDraft({...draftFixture,content:{shifts:[...new Map([...reviews.values()].flatMap(r=>r.content?.shifts??[]).map(s=>[s.id,s])).values()],sections:[...reviews.values()].flatMap(r=>r.content?.sections??[]),structurePhotos:[...new Map([...reviews.values()].flatMap(r=>r.content?.structurePhotos??[]).map(p=>[p.mediaId,p])).values()]},issues:[]});session=asSession({...session,status:'COMPLETED',phase:'COMPLETED',completedAt:new Date().toISOString(),processing:null});}data=draft;break}
   case 'generateManualDraft':{const request=input as {expectedRevision:number;reviewRevisions:{intentId:string;revision:number}[]};if(request.expectedRevision!==session.revision||request.reviewRevisions.some(i=>reviews.get(i.intentId)?.revision!==i.revision))throw new ManualError('REVISION_CONFLICT');if(session.phase!=='READY_TO_GENERATE'||[...reviews.values()].some(r=>r.status!=='READY'))throw new ManualError('REVIEW_NOT_READY');session=asSession({...session,revision:session.revision+1,phase:'GENERATING',processing:{taskId:crypto.randomUUID(),kind:'DRAFT_GENERATION',attempt:1}});draft=asDraft({...draft,generationStatus:'RUNNING',content:null});data=session;break}
   case 'retryManualInterviewProcessing':{if((input as {expectedRevision:number}).expectedRevision!==session.revision)throw new ManualError('REVISION_CONFLICT');if(session.phase!=='ERROR')throw new ManualError('MANUAL_STATE_CONFLICT');session=asSession({...session,revision:session.revision+1,status:'IN_PROGRESS',phase:'GENERATING',error:null,completedAt:null,processing:{...session.processing,kind:'DRAFT_GENERATION',attempt:session.processing!.attempt+1}});draft=asDraft({...draft,generationStatus:'RUNNING',content:null});data=session;break}
   case 'startManualInterview':started=true;data=session;break
   case 'getManualInterview':{
    if(session.phase==='PROCESSING'){
     const index=session.intents.findIndex(i=>i.id===session.currentIntentId),intent=session.intents[index]
     if(count%2===1)session=asSession({...session,status:'IN_PROGRESS',error:null,completedAt:null,phase:'COLLECTING',revision:session.revision+1,processing:null,questions:[{id:crypto.randomUUID(),intentId:intent.id,kind:'PROBE',depth:1,batchId:crypto.randomUUID(),text:'처음 일하는 근무자도 따라 할 수 있게 조금 더 알려주세요.',answered:false}]})
     else {finishIntent(index);const next=session.intents[index+1];session=asSession({...session,status:'IN_PROGRESS',error:null,completedAt:null,phase:next?'COLLECTING':'READY_TO_GENERATE',revision:session.revision+1,processing:null,currentIntentId:next?.id??null,questions:next?[{id:crypto.randomUUID(),intentId:next.id,kind:'BASE',depth:0,batchId:null,text:['','모두가 하는 일은 무엇인가요?','근무조별로 다른 일은 무엇인가요?','규정과 설비 사용 방법을 알려주세요.'][index+1],answered:false}]:[]})}
    }
    data=session;break
   }
   case 'uploadManualMedia':{const file=(input as FormData).get('file') as Blob,id=crypto.randomUUID();media.set(id,file);data={id,storeId:manualStoreId,purpose:(input as FormData).get('purpose'),mimeType:file.type,sizeBytes:file.size,createdAt:new Date().toISOString()};break}
   case 'readManualPhoto':{const blob=media.get(params.mediaId);data=blob??new Blob([Uint8Array.from(atob('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+j7XcAAAAASUVORK5CYII='),c=>c.charCodeAt(0))],{type:'image/png'});break}
   case 'createManualTranscription':{const id=crypto.randomUUID();transcriptions.set(id,(input as {mediaId:string}).mediaId);data={id,mediaId:(input as {mediaId:string}).mediaId,status:'RUNNING',text:null,error:null,createdAt:new Date().toISOString(),completedAt:null};break}
   case 'getManualTranscription':data={id:params.transcriptionId,mediaId:transcriptions.get(params.transcriptionId),status:'READY',text:'샘플 음성 답변',error:null,createdAt:new Date().toISOString(),completedAt:new Date().toISOString()};break
   case 'answerManualInterviewQuestion':{const answer=input as ManualInterviewAnswer;if(answer.expectedRevision!==session.revision||answer.questionId!==session.questions[0]?.id)throw new ManualError('REVISION_CONFLICT');count++;turns.push({id:crypto.randomUUID(),sequence:++sequence,intentId:session.currentIntentId!,kind:'ANSWER',speaker:'OWNER',questionKind:null,depth:session.questions[0].depth,batchId:null,replyToQuestionId:answer.questionId,inputMethod:'VOICE',content:'샘플 음성 답변',photoIds:[],createdAt:new Date().toISOString()});session=asSession({...session,revision:session.revision+1,status:'IN_PROGRESS',error:null,completedAt:null,phase:'PROCESSING',questions:[],processing:{taskId:crypto.randomUUID(),kind:'EVALUATION',attempt:1}});data=session;break}
   case 'listManualIntentReviews':data={sessionId:session.id,sessionRevision:session.revision,items:[...reviews.values()]};break
   case 'getManualIntentReview':data=reviews.get(params.intentId);break
   case 'replaceManualInterviewReviewPhotos':{const r=reviews.get(params.intentId)!,update=input as ManualInterviewPhotoUpdate;if(update.expectedRevision!==r.revision)throw new ManualError('REVISION_CONFLICT');if(r.status!=='READY'||!r.content)throw new ManualError('MANUAL_STATE_CONFLICT');if(update.target==='SECTION'&&!r.content.sections.some(s=>s.id===update.sectionId))throw new ManualError('MANUAL_REFERENCE_CONFLICT');data={...r,revision:r.revision+1,confirmedAt:null,content:{...r.content,...(update.target==='WORK_STRUCTURE'?{structurePhotos:update.photos}:{sections:r.content.sections.map(section=>section.id===update.sectionId?{...section,photos:update.photos}:section)})}};reviews.set(params.intentId,data as ManualIntentReview);break}
   case 'correctManualInterviewUnderstanding':{const r=reviews.get(params.intentId)!,correction=input as ManualInterviewCorrection;if(correction.expectedRevision!==r.revision)throw new ManualError('REVISION_CONFLICT');data={...r,revision:r.revision+1,status:'READY',confirmedAt:null,content:{...r.content,summary:'수정한 내용을 반영했어요. 야간조는 오전 6시에 끝나요.',shifts:r.content!.shifts.map(shift=>({...shift,endTime:'06:00'}))}};reviews.set(params.intentId,data as ManualIntentReview);break}
   case 'confirmManualInterviewUnderstanding':{const r=reviews.get(params.intentId)!;data={...r,revision:r.revision+1,confirmedAt:new Date().toISOString()};reviews.set(params.intentId,data as ManualIntentReview);break}
   case 'retryManualIntentReview':{const r=reviews.get(params.intentId)!;data={...r,revision:r.revision+1,status:'READY',error:null,processing:null};reviews.set(params.intentId,data as ManualIntentReview);break}
   case 'getManualInterviewTurns':data={items:turns,page:0,size:100,totalItems:turns.length,totalPages:turns.length?1:0,asOf:new Date().toISOString()};break
   case 'createManualDraftCorrection':{const request=input as ManualDraftCorrectionInput;if(request.expectedVersionId!==draft.versionId)throw new ManualError('MANUAL_VERSION_CONFLICT');if(request.expectedRevision!==draft.revision)throw new ManualError('REVISION_CONFLICT');if(draft.latestCorrection?.status==='RUNNING')throw new ManualError('MANUAL_CORRECTION_IN_PROGRESS');const job=asJob({id:crypto.randomUUID(),versionId:draft.versionId,baseRevision:draft.revision,target:request.target,status:'RUNNING',attempt:1,resultRevision:null,error:null,createdAt:new Date().toISOString(),completedAt:null});draft=asDraft({...draft,latestCorrection:job});data=job;break}
   case 'getManualDraftCorrection':{const job=draft.latestCorrection;if(!job||job.id!==params.correctionId)throw new ManualError('MANUAL_RESOURCE_NOT_FOUND');if(job.status==='RUNNING'&&scenario!=='correction-running'){if(['correction-error','correction-clarify'].includes(scenario)&&job.attempt===1){draft=asDraft({...draft,latestCorrection:asJob({...job,status:'ERROR',error:{code:scenario==='correction-error'?'AI_PROCESSING_FAILED':'CORRECTION_CLARIFICATION_REQUIRED',message:'샘플 정정 실패',retryable:scenario==='correction-error'},completedAt:new Date().toISOString()})})}else{const noop=scenario==='correction-noop'||scenario==='noop-missing',revision=draft.revision+(noop?0:1),removed=draft.content!.missingInformation?.filter(item=>job.target.kind!=='SECTION'&&item.target==='SHIFT'&&item.field==='endTime'&&(job.target.kind==='MANUAL'||item.targetId===job.target.targetId)).map(item=>item.id)??[];draft=asDraft({...draft,revision,content:noop?draft.content:{...draft.content,shifts:draft.content!.shifts.map(shift=>job.target.kind==='MANUAL'||job.target.kind==='SHIFT'&&job.target.targetId===shift.id?{...shift,endTime:'06:00'}:shift),sections:draft.content!.sections.map(section=>job.target.kind==='SECTION'&&section.id===job.target.targetId?{...section,steps:section.steps.map(step=>({...step,instruction:'물품의 유통기한을 먼저 확인하세요.'}))}:section),missingInformation:draft.content!.missingInformation?.filter(item=>!removed.includes(item.id))??[]},issues:noop?draft.issues:draft.issues.filter(issue=>!removed.includes(issue.id)).map(issue=>({...issue,status:'OPEN',ownerNote:null,acknowledgedAt:null})),latestCorrection:asJob({...job,status:'SUCCEEDED',resultRevision:revision,completedAt:new Date().toISOString()})})}}data=draft.latestCorrection;break}
   case 'retryManualDraftCorrection':{const job=draft.latestCorrection,request=input as {expectedVersionId:string;expectedRevision:number};if(request.expectedVersionId!==draft.versionId)throw new ManualError('MANUAL_VERSION_CONFLICT');if(request.expectedRevision!==draft.revision||job?.baseRevision!==draft.revision)throw new ManualError('REVISION_CONFLICT');if(job.id!==params.correctionId||job.status!=='ERROR'||!job.error.retryable)throw new ManualError('MANUAL_CORRECTION_NOT_RETRYABLE');draft=asDraft({...draft,latestCorrection:asJob({...job,status:'RUNNING',attempt:job.attempt+1,error:null,completedAt:null})});data=draft.latestCorrection;break}
   case 'replaceManualDraftContent':{const request=input as Operations['replaceManualDraftContent']['input'];if(request.expectedVersionId!==draft.versionId)throw new ManualError('MANUAL_VERSION_CONFLICT');if(request.expectedRevision!==draft.revision)throw new ManualError('REVISION_CONFLICT');if(draft.latestCorrection?.status==='RUNNING')throw new ManualError('MANUAL_CORRECTION_IN_PROGRESS');draft=asDraft({...draft,revision:draft.revision+1,content:request.content,issues:draft.issues.map(issue=>({...issue,status:'OPEN',acknowledgedAt:null,ownerNote:null}))});data=draft;break}
   case 'previewManualForWorker':{if(draft.generationStatus!=='READY')throw new ManualError('MANUAL_STATE_CONFLICT');data={preview:true,versionId:draft.versionId,revision:draft.revision,content:draft.content};break}
   case 'acknowledgeManualIssues':{const request=input as ManualIssueAcknowledgement;if(request.expectedVersionId!==draft.versionId)throw new ManualError('MANUAL_VERSION_CONFLICT');if(request.expectedRevision!==draft.revision)throw new ManualError('REVISION_CONFLICT');if(draft.latestCorrection?.status==='RUNNING')throw new ManualError('MANUAL_CORRECTION_IN_PROGRESS');draft=asDraft({...draft,revision:draft.revision+1,issues:draft.issues.map(issue=>request.issueIds.includes(issue.id)?{...issue,status:'ACKNOWLEDGED',acknowledgedAt:new Date().toISOString()}:issue)});data=draft;break}
   case 'publishManualDraft':{const request=input as ManualPublishInput;if(request.expectedVersionId!==draft.versionId)throw new ManualError('MANUAL_VERSION_CONFLICT');if(request.expectedRevision!==draft.revision)throw new ManualError('REVISION_CONFLICT');publicationInput(draft);data={versionId:draft.versionId,storeId:manualStoreId,versionNumber:draft.versionNumber,status:'PUBLISHED',ownerConfirmed:true,content:draft.content,publishedAt:new Date().toISOString()};publishedId=draft.versionId;break}
   default:throw new ManualError('PREVIEW_NOT_IMPLEMENTED')
  }
  if(options.key)results.set(options.key,structuredClone(data))
  return {data:structuredClone(data) as Operations[N]['output'],retryAfterMs:2000}
 }}
}
