import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react'
import {afterEach,beforeEach,expect,it,vi} from 'vitest'
import {OwnerRequestWithdrawal} from './OwnerRequestWithdrawal'
import data from './ownerJob.fixture.test.json'
import type {JobPosting,WorkRequest} from '../api/types.generated'
const json=(v:unknown,status=200)=>new Response(JSON.stringify(v),{status})
beforeEach(()=>{Object.defineProperty(HTMLDialogElement.prototype,'showModal',{configurable:true,value:function(){this.setAttribute('open','')}});Object.defineProperty(HTMLDialogElement.prototype,'close',{configurable:true,value:function(){this.removeAttribute('open')}})})
afterEach(()=>{cleanup();vi.unstubAllGlobals();Reflect.deleteProperty(HTMLDialogElement.prototype,'showModal');Reflect.deleteProperty(HTMLDialogElement.prototype,'close')})
it.each([false,true])('요청/확정 철회 %s에서 현재 revision·CSRF·멱등 키를 전달하고 중복 클릭을 차단한다',async confirmed=>{
 const request=(confirmed?data.confirmedRequests:data.requests).items[0] as WorkRequest,job={...(confirmed?data.confirmedJob:data.job),startAt:'2099-10-10T00:00:00Z'} as JobPosting
 const writes:RequestInit[]=[];const fetch=vi.fn(async(url:unknown,init?:RequestInit)=>{if(String(url).includes('csrf'))return json({csrfToken:'token'});writes.push(init!);return json({...request,status:confirmed?'CONFIRMATION_WITHDRAWN':'CANCELLED',endedAt:'2026-10-08T00:00:00Z'})});vi.stubGlobal('fetch',fetch);const complete=vi.fn();render(<OwnerRequestWithdrawal job={job} request={request} storeId={job.store.id} onClose={vi.fn()} onCompleted={complete} onReload={vi.fn()}/>);const button=screen.getByRole('button',{name:confirmed?'확정 철회':'요청 철회'});fireEvent.click(button);fireEvent.click(button);await waitFor(()=>expect(complete).toHaveBeenCalledOnce());expect(writes).toHaveLength(1);expect(JSON.parse(writes[0].body as string)).toEqual({expectedRevision:request.revision});expect(new Headers(writes[0].headers).get('X-CSRF-Token')).toBe('token');expect(new Headers(writes[0].headers).get('Idempotency-Key')).toBeTruthy();expect(fetch.mock.calls.some(([url])=>String(url).includes(confirmed?'confirmation-withdrawal':'/withdrawal'))).toBe(true)
})
it('응답 손실 재시도에 같은 키를 유지하고 충돌에서는 최신 조회를 제공한다',async()=>{
 let attempts=0;const keys:(string|null)[]=[];const request=data.requests.items[0] as WorkRequest,job=data.job as JobPosting;vi.stubGlobal('fetch',vi.fn(async(url:unknown,init?:RequestInit)=>{if(String(url).includes('csrf'))return json({csrfToken:'token'});keys.push(new Headers(init?.headers).get('Idempotency-Key'));attempts++;if(attempts===1)throw Error('lost');return json({code:'REVISION_CONFLICT'},409)}));const complete=vi.fn(),reload=vi.fn();render(<OwnerRequestWithdrawal job={job} request={request} storeId={job.store.id} onClose={vi.fn()} onCompleted={complete} onReload={reload}/>);fireEvent.click(screen.getByRole('button',{name:'요청 철회'}));await screen.findByRole('alert');fireEvent.click(screen.getByRole('button',{name:'요청 철회'}));await waitFor(()=>expect(keys).toHaveLength(2));expect(keys[1]).toBe(keys[0]);expect(complete).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'최신 상태 확인'}));expect(reload).toHaveBeenCalledOnce()
})
it('시작한 확정 근무는 변경 요청을 보내지 않는다',async()=>{const fetch=vi.fn();vi.stubGlobal('fetch',fetch);render(<OwnerRequestWithdrawal job={{...data.confirmedJob,startAt:'2000-01-01T00:00:00Z'} as JobPosting} request={data.confirmedRequests.items[0] as WorkRequest} storeId={data.job.store.id} onClose={vi.fn()} onCompleted={vi.fn()} onReload={vi.fn()}/>);fireEvent.click(screen.getByRole('button',{name:'확정 철회'}));await screen.findByRole('alert');expect(fetch).not.toHaveBeenCalled()})
