import { useId,useState } from 'react'
import { MobileLayout } from '../ui/MobileLayout'
import { AppBar } from '../ui/AppBar'
import { Button } from '../ui/Button'
import { Tabs } from '../ui/Tabs'
import { Modal } from '../ui/Modal'
import { useInvitationCommand } from './useInvitationCommand'
import type { Invitation } from './model'
import './Invitation.css'
export type InvitationManagementService={cancel:(id:string,signal:AbortSignal)=>Promise<void>;resend:(id:string,signal:AbortSignal)=>Promise<void>}
const unavailable:InvitationManagementService={cancel:async()=>{throw Error('INVITATIONS_NOT_CONFIGURED')},resend:async()=>{throw Error('INVITATIONS_NOT_CONFIGURED')}}
const statusLabels={pending:'수락 대기',accepted:'수락 완료',expired:'기간 만료',cancelled:'초대 취소',declined:'수락 거절'}
export function InvitationManagement({storeName,invitations,onBack,onCreate,onCancelled,service=unavailable,initialTab=0,initialOverlay}: {storeName:string;invitations:readonly Invitation[];onBack:()=>void;onCreate:(email?:string)=>void;onCancelled:(id:string)=>void;service?:InvitationManagementService;initialTab?:number;initialOverlay?:'cancel'|'resent'}) {
 const [selected,setSelected]=useState(initialTab),[cancelTarget,setCancelTarget]=useState<Invitation|null>(()=>initialOverlay==='cancel'?invitations.find(item=>item.status==='pending')??null:null),[resent,setResent]=useState<Invitation|null>(()=>initialOverlay==='resent'?invitations.find(item=>item.status==='pending')??null:null)
 const {busy,failed,run,cancel}=useInvitationCommand(),panelId=useId()
 const active=invitations.filter(item=>item.status==='pending'),items=selected===0?active:invitations.filter(item=>item.status!=='pending')
 function closeCancel(){cancel();setCancelTarget(null)}
 async function confirmCancel(){if(!cancelTarget)return;const target=cancelTarget;if(!await run(signal=>service.cancel(target.id,signal),()=>onCancelled(target.id)))throw Error('CANCEL_FAILED')}
 function resend(item:Invitation){void run(signal=>service.resend(item.id,signal),()=>setResent(item))}
 return <><MobileLayout className="invitation-screen invitation-management" header={<AppBar title="근무자 초대 관리" compact onBack={onBack}/>} footer={selected===0?<Button onClick={()=>onCreate()}>새 근무자 초대</Button>:undefined}><div className="invitation-content"><div className="invitation-heading"><h2>보낸 초대를 관리하세요</h2><p>{storeName}</p></div><Tabs labels={[`활성 초대 ${active.length}`,'지난 초대']} selected={selected} onSelect={setSelected} panelId={panelId} label="초대 상태"/><div role="tabpanel" id={panelId} aria-labelledby={`${panelId}-tab-${selected}`} className="invitation-list">{items.map(item=><article className="invitation-card invitation-list-card" key={item.id}><div className="invitation-card-heading"><strong>{item.email}</strong><span className={`invitation-badge invitation-badge-${item.status}`}>{statusLabels[item.status]}</span></div>{selected===0?<><div className="invitation-dates"><p>보낸 날짜&nbsp; {item.sentAt}</p><p>유효 기간&nbsp; {item.expiresAt}</p></div><div className="invitation-actions"><Button intent="secondary" disabled={busy} onClick={()=>resend(item)}>다시 보내기</Button><Button intent="secondary" disabled={busy} onClick={()=>setCancelTarget(item)}>초대 취소</Button></div></>:<><p className={`invitation-history${item.status==='accepted'?'':' invitation-history-secondary'}`}>{item.status==='accepted'?`${item.respondedAt??''} 수락 · ${item.workerName??item.email}`:`${item.sentAt} 발송 · ${item.expiresAt} ${statusLabels[item.status]}`}</p>{item.status==='expired'&&<Button intent="secondary" onClick={()=>onCreate(item.email)}>새로 초대하기</Button>}</>}</article>)}{!items.length&&<section className="invitation-card invitation-empty"><h3>{selected===0?'대기 중인 초대가 없어요':'지난 초대가 없어요'}</h3><p>{selected===0?'함께 일할 근무자를 새로 초대해 주세요.':'완료된 초대는 여기에 표시돼요.'}</p></section>}</div>{selected===0&&<p className="invitation-notice">초대는 생성 후 7일간 유효해요.<br/>취소하면 기존 초대 링크를 사용할 수 없어요.</p>}{failed&&!cancelTarget&&<p className="invitation-error" role="alert">처리하지 못했어요. 다시 시도해 주세요.</p>}</div></MobileLayout><Modal open={cancelTarget!==null} state="warning" title="초대를 취소할까요?" description={`${cancelTarget?.email??''}으로 보낸\n초대 링크를 더 이상 사용할 수 없어요.`} cancelLabel="돌아가기" confirmLabel="초대 취소" busy={busy} onClose={closeCancel} onConfirm={confirmCancel}/><Modal open={resent!==null} title="초대를 다시 보냈어요" description={`${resent?.email??''}에서 메일을 확인할 수 있어요.\n기존 초대의 유효 기간은 그대로 유지돼요.`} onClose={()=>setResent(null)}/></>
}
