import { useState } from 'react'
import { act,fireEvent,render,screen,waitFor,within } from '@testing-library/react'
import { expect,it,vi } from 'vitest'
import { mockDialog } from '../jobs/dialogTestSupport'
import { InvitationManagement,type InvitationManagementService } from './InvitationManagement'
import type { Invitation } from './model'
mockDialog()
const pending:Invitation={id:'one',email:'minji@example.com',storeName:'매장',sentAt:'9월 25일',expiresAt:'10월 2일까지',accessUntil:'2026. 09. 26까지',status:'pending'}
function Sample({service,items=[pending]}:{service:InvitationManagementService;items?:Invitation[]}){const [data,setData]=useState(items);return <InvitationManagement storeName="매장" invitations={data} service={service} onBack={()=>{}} onCreate={()=>{}} onCancelled={id=>setData(data.map(item=>item.id===id?{...item,status:'cancelled'}:item))}/>}
it('취소 확인을 닫으면 상태를 유지하고 성공 이후에만 건수를 변경한다',async()=>{const cancel=vi.fn().mockResolvedValue(undefined);render(<Sample service={{cancel,resend:vi.fn()}}/>);fireEvent.click(screen.getByRole('button',{name:'초대 취소'}));fireEvent.click(screen.getByRole('button',{name:'돌아가기'}));expect(cancel).not.toHaveBeenCalled();expect(screen.getByRole('tab',{name:'활성 초대 1'})).toBeVisible();fireEvent.click(screen.getByRole('button',{name:'초대 취소'}));fireEvent.click(within(screen.getByRole('alertdialog')).getByRole('button',{name:'초대 취소'}));await screen.findByRole('tab',{name:'활성 초대 0'});expect(screen.getByText('대기 중인 초대가 없어요')).toBeVisible();await waitFor(()=>expect(screen.getByRole('heading',{name:'보낸 초대를 관리하세요'})).toHaveFocus())})
it('취소 실패와 ESC는 기존 데이터를 유지한다',async()=>{const cancel=vi.fn().mockRejectedValue(Error());render(<Sample service={{cancel,resend:vi.fn()}}/>);fireEvent.click(screen.getByRole('button',{name:'초대 취소'}));fireEvent.click(within(screen.getByRole('alertdialog')).getByRole('button',{name:'초대 취소'}));await screen.findByRole('alert');fireEvent(screen.getByRole('alertdialog'),new Event('cancel',{cancelable:true}));expect(screen.getByRole('tab',{name:'활성 초대 1'})).toBeVisible()})
it('재전송 중 중복을 막고 유효 기간을 변경하지 않는다',async()=>{let resolve!:()=>void;const resend=vi.fn(()=>new Promise<void>(r=>{resolve=r}));render(<Sample service={{cancel:vi.fn(),resend}}/>);fireEvent.click(screen.getByRole('button',{name:'다시 보내기'}));fireEvent.click(screen.getByRole('button',{name:'다시 보내기'}));expect(resend).toHaveBeenCalledOnce();await act(async()=>resolve());expect(screen.getByRole('dialog',{name:'초대를 다시 보냈어요'})).toBeVisible();expect(screen.getByText(/유효 기간.*10월 2일까지/)).toBeVisible()})
it('만료 초대에서 새 생성 동작으로 이동한다',()=>{const create=vi.fn();render(<InvitationManagement storeName="매장" invitations={[{...pending,status:'expired'}]} initialTab={1} onBack={()=>{}} onCreate={create} onCancelled={()=>{}}/>);expect(screen.queryByRole('button',{name:'다시 보내기'})).not.toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'새로 초대하기'}));expect(create).toHaveBeenCalledWith(pending.email)})
