import {useManualInterview} from './useManualInterview'
import {Button} from '../ui/Button'
import {ManualFrame,ManualCard} from './ManualFrame'
import {ManualVoiceComposer} from './ManualVoiceComposer'
import {ManualContentView} from './ManualContentView'
import type {ManualService} from './service'
import type {ManualInterviewSession} from './types'
import {ManualReviewPhotos} from './ManualReviewPhotos'
export function ManualInterview({service,initial,onBack,onFinal,onDraft}:{service:ManualService;initial:ManualInterviewSession;onBack:()=>void;onFinal?:(session:ManualInterviewSession)=>void;onDraft?:(versionId:string)=>void}){
 const {session,reviews,setSelected,correcting,setCorrecting,pollError,reviewError,turns,showHistory,setRefresh,photoTarget,setPhotoTarget,task,historyTask,current,review,stage,updateReview,submit,reviewCommand,loadHistory,ready,setSession}=useManualInterview({service,initial,onFinal,onDraft})
 const footer=review?correcting?<ManualVoiceComposer key={review.intentId+':correction'} onRecording={submit} label="말해서 답하기"/>:<div className="manual-stack"><div className="manual-button-row"><Button intent="secondary" disabled={task.busy||review.status!=='READY'} onClick={()=>setCorrecting(true)}>수정할게요</Button><Button busy={task.busy} disabled={review.status!=='READY'} onClick={()=>reviewCommand('confirmManualInterviewUnderstanding')}>네, 맞아요</Button></div><Button intent="secondary" onClick={()=>{setSelected(null);setCorrecting(false)}}>나중에 확인하기</Button></div>:session.phase==='COLLECTING'?<ManualVoiceComposer key={session.questions[0]?.id} onRecording={submit}/>:session.phase==='ERROR'?<Button busy={task.busy} onClick={()=>void task.run(async(signal,key)=>{const result=await service.call('retryManualInterviewProcessing',{sessionId:session.id},{expectedRevision:session.revision},{signal,key});if(!signal.aborted)setSession(old=>result.data.revision>=old.revision?result.data:old)})}>답변 처리 다시 시도</Button>:session.phase==='READY_TO_GENERATE'?<Button disabled={!ready||!onFinal} onClick={()=>onFinal?.(current.current)}>최종 검토로</Button>:<p className="manual-voice-title" role="status">답변을 정리하고 있어요</p>
 if(photoTarget&&review)return <ManualReviewPhotos service={service} sessionId={session.id} review={review} target={photoTarget} onUpdate={updateReview} onClose={()=>setPhotoTarget(null)}/>
 return <ManualFrame onBack={onBack} stage={stage} footer={footer}><div className="manual-stack">
  {review?<><h2 className="manual-heading">{correcting?'어떤 부분을\n고치면 될까요?':'이렇게 이해했어요'}</h2><p className="manual-muted">{correcting?'다르게 정리된 내용을 말해 주세요.':'내용이 맞는지 확인해 주세요.'}</p>{review.content&&<><ManualCard title="정리한 내용"><p className="manual-question">{review.content.summary}</p></ManualCard><ManualContentView content={review.content} service={service}/></>}{review.status==='PROCESSING'&&<p role="status">요약을 정리하고 있어요.</p>}{review.status==='ERROR'&&<><p role="alert">요약을 정리하지 못했어요. 질문은 계속 답할 수 있어요.</p><Button busy={task.busy} onClick={()=>reviewCommand('retryManualIntentReview')}>요약 다시 시도</Button></>}{!correcting&&review.status==='READY'&&review.content&&<><Button intent="secondary" onClick={()=>setPhotoTarget({target:'WORK_STRUCTURE',sectionId:null})}>근무 구조 사진 첨부</Button>{review.content.sections.map(section=><Button key={section.id} intent="secondary" onClick={()=>setPhotoTarget({target:'SECTION',sectionId:section.id})}>{section.title} 사진 첨부</Button>)}</>}</>:<><h2 className="manual-heading">{session.questions[0]?.text??(session.phase==='READY_TO_GENERATE'?'모든 질문에 답했어요.':'답변을 정리하고 있어요')}</h2>{session.questions[0]?.kind==='PROBE'&&<p className="manual-muted">추가로 알려주세요. ({session.questions[0].depth}/5)</p>}</>}
  {session.intents.some(i=>i.coverage==='NEEDS_DETAIL')&&<p className="manual-muted">정보가 부족한 주제는 최종 검토에서 확인할 수 있어요.</p>}
  {!correcting&&reviews?.items.map(r=><Button key={r.intentId} intent="secondary" onClick={()=>{setSelected(r.intentId);setCorrecting(false);task.clearError()}}>정리한 내용 확인 · {session.intents.find(i=>i.id===r.intentId)?.key??'이전 주제'}{r.status==='ERROR'?' · 다시 시도 필요':''}</Button>)}
  {(pollError||reviewError)&&<><p role="alert">{pollError||reviewError}</p><Button intent="secondary" onClick={()=>setRefresh(v=>v+1)}>최신 내용 다시 불러오기</Button></>}{task.error&&<><p role="alert">{task.error}</p>{task.canRetry&&<Button intent="secondary" onClick={task.retry}>요청 다시 시도</Button>}</>}
  <Button intent="secondary" busy={historyTask.busy} onClick={()=>void loadHistory()}>질문·답변 이력</Button>{historyTask.error&&<p role="alert">{historyTask.error}</p>}{showHistory&&<ol className="manual-history">{turns.map(t=><li key={t.id}>{t.kind==='QUESTION'?t.content:t.kind==='CORRECTION'?'음성 수정 완료':'음성 답변 완료'}</li>)}</ol>}
 </div></ManualFrame>
}
