import { act, fireEvent, render, screen, cleanup } from '@testing-library/react'
import { afterEach, beforeAll, expect, it, vi } from 'vitest'
import { ValuePicker } from './ValuePicker'
beforeAll(() => { HTMLDialogElement.prototype.showModal = function () { this.open = true }; HTMLDialogElement.prototype.close = function () { this.open = false } })
afterEach(cleanup)
it('연월의 경계를 제한하고 연도 변경 시 가능한 월로 보정한다', () => {
 const save = vi.fn()
 render(<ValuePicker title="시작 연월" type="month" value="2024-12" min="2023-03" max="2025-02" onClose={()=>{}} onSave={save} />)
 fireEvent.keyDown(screen.getByRole('spinbutton',{name:'연도'}),{key:'End'})
 expect(screen.getByRole('spinbutton',{name:'월'}).getAttribute('aria-valuenow')).toBe('2')
 fireEvent.keyDown(screen.getByRole('spinbutton',{name:'월'}),{key:'ArrowDown'})
 fireEvent.click(screen.getByRole('button',{name:'선택 완료'}))
 expect(save).toHaveBeenCalledWith('2025-02',false)
})
it('종료 연월에서 현재 근무 중을 선택하고 다시 해제할 수 있다', () => {
 const save = vi.fn()
 render(<ValuePicker title="종료 연월" type="month" value="2024-12" min="2024-03" max="2025-02" current={false} onClose={()=>{}} onSave={save} />)
 const year = screen.getByRole('spinbutton', {name:'연도'})
 const option = screen.getByRole('checkbox', {name:'현재 근무 중'})
 expect(screen.getByRole('spinbutton', {name:'월'}).compareDocumentPosition(option) & Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy()
 expect(option.compareDocumentPosition(screen.getByRole('button',{name:'선택 완료'})) & Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy()
 const selectedYear = year.getAttribute('aria-valuenow')
 fireEvent.click(screen.getByRole('checkbox', {name:'현재 근무 중'}))
 expect(year).toHaveAttribute('aria-disabled','true')
 fireEvent.keyDown(year,{key:'End'})
 expect(year).toHaveAttribute('aria-valuenow', selectedYear)
 fireEvent.click(screen.getByRole('checkbox', {name:'현재 근무 중'}))
 expect(year).not.toHaveAttribute('aria-disabled')
 fireEvent.keyDown(year,{key:'End'})
 expect(year).toHaveAttribute('aria-valuenow','2025')
 fireEvent.click(screen.getByRole('checkbox', {name:'현재 근무 중'}))
 fireEvent.click(screen.getByRole('button',{name:'선택 완료'}))
 expect(save).toHaveBeenCalledWith('2025-02',true)
})
it('자정과 30분 및 다음 날 종료를 확인할 때만 저장한다', () => {
 const save=vi.fn(),close=vi.fn()
 render(<ValuePicker title="종료 시간" type="time" value="1410" overnight={false} onClose={close} onSave={save} />)
 fireEvent.keyDown(screen.getByRole('spinbutton'),{key:'Home'})
 fireEvent.click(screen.getByRole('button',{name:'00분'}))
 fireEvent.click(screen.getByRole('checkbox',{name:'다음 날 종료'}))
 expect(screen.getByRole('spinbutton',{name:'시 · 24시간제'})).toHaveAttribute('aria-disabled','true')
 expect(screen.getByRole('button',{name:'30분'})).toBeDisabled()
 fireEvent.keyDown(screen.getByRole('spinbutton',{name:'시 · 24시간제'}),{key:'End'})
 expect(screen.getByRole('spinbutton',{name:'시 · 24시간제'})).toHaveAttribute('aria-valuenow','0')
 expect(save).not.toHaveBeenCalled()
 fireEvent.click(screen.getByRole('button',{name:'선택 완료'}))
 expect(save).toHaveBeenCalledWith('0',true)
 expect(close).toHaveBeenCalledOnce()
})
it('다음 날 종료를 해제하면 이전에 선택한 시간을 유지하며 다시 수정할 수 있다', () => {
 const save=vi.fn()
 render(<ValuePicker title="종료 시간" type="time" value="870" overnight={true} onClose={()=>{}} onSave={save} />)
 expect(screen.getByRole('spinbutton',{name:'시 · 24시간제'})).toHaveAttribute('aria-valuenow','14')
 expect(screen.getByRole('button',{name:'30분'})).toHaveAttribute('aria-pressed','true')
 fireEvent.click(screen.getByRole('checkbox',{name:'다음 날 종료'}))
 expect(screen.getByRole('spinbutton',{name:'시 · 24시간제'})).not.toHaveAttribute('aria-disabled')
 fireEvent.click(screen.getByRole('button',{name:'00분'}))
 fireEvent.click(screen.getByRole('button',{name:'선택 완료'}))
 expect(save).toHaveBeenCalledWith('840',false)
})
it('닫기는 선택을 저장하지 않으며 시작 시간에는 다음 날 옵션이 없다',()=>{
 const save=vi.fn(),close=vi.fn()
 render(<ValuePicker title="시작 시간" type="time" value="540" onSave={save} onClose={close} />)
 expect(screen.queryByRole('checkbox')).toBeNull()
 fireEvent.keyDown(screen.getByRole('spinbutton'),{key:'ArrowDown'})
 fireEvent.click(screen.getByRole('button',{name:'닫기'}))
 expect(save).not.toHaveBeenCalled();expect(close).toHaveBeenCalledOnce()
})

it('스크롤 도중 값이 변경되어도 오프셋을 강제로 되돌리지 않는다', () => {
 vi.useFakeTimers()
 try {
  render(<ValuePicker title="시작 시간" type="time" value="540" onSave={()=>{}} onClose={()=>{}} />)
  act(()=>vi.runOnlyPendingTimers())
  const wheel=screen.getByRole('spinbutton')
  wheel.scrollTop=430
  fireEvent.scroll(wheel)
  expect(wheel).toHaveAttribute('aria-valuenow','11')
  act(()=>vi.runOnlyPendingTimers())
  expect(wheel.scrollTop).toBe(430)
  fireEvent.keyDown(wheel,{key:'ArrowDown'})
  act(()=>vi.runOnlyPendingTimers())
  expect(wheel.scrollTop).toBe(480)
 } finally { vi.useRealTimers() }
})

it('공고에서는 다음 날 종료를 선택해도 종료 시각을 바꿀 수 있다',()=>{const save=vi.fn();render(<ValuePicker title="종료 시간" type="time" value="360" overnight={true} allowNextDayTime onClose={()=>{}} onSave={save}/>);expect(screen.getByRole('spinbutton',{name:'시 · 24시간제'})).not.toHaveAttribute('aria-disabled');fireEvent.click(screen.getByText('30분'));fireEvent.click(screen.getByText('선택 완료'));expect(save).toHaveBeenCalledWith('390',true)})
