import {act,cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react'
import {afterEach,beforeEach,expect,it,vi} from 'vitest'
import {OwnerJobList} from './OwnerJobList'
import {JobCloseFlow} from './JobCloseFlow'
import type {OwnerJob} from './model'
const job={id:'open',title:'오픈',storeName:'매장',date:'2026-09-27',start:'09:00',end:'14:00',nextDay:false,applicants:0,publishedAt:'2026-09-01',status:'recruiting'} as OwnerJob
beforeEach(()=>{Object.defineProperty(HTMLDialogElement.prototype,'showModal',{configurable:true,value:function(){this.setAttribute('open','')}});Object.defineProperty(HTMLDialogElement.prototype,'close',{configurable:true,value:function(){this.removeAttribute('open')}})})
afterEach(()=>{cleanup();Reflect.deleteProperty(HTMLDialogElement.prototype,'showModal');Reflect.deleteProperty(HTMLDialogElement.prototype,'close')})
it('상태별 집계·최근 등록순·선정 완료를 표시한다',()=>{render(<OwnerJobList storeName="매장" jobs={[job,{...job,id:'new',title:'최근 공고',publishedAt:'2026-09-02'},{...job,id:'selected',status:'selected'}]} onBack={vi.fn()} onSelect={vi.fn()}/>);expect(screen.getByText('모집 중 2')).toBeVisible();expect(document.querySelectorAll('.owner-job-card')[0]).toHaveTextContent('최근 공고');fireEvent.click(screen.getByText('마감 1'));expect(screen.getByText('선정 완료')).toBeVisible();expect(screen.queryByText('최근 공고')).toBeNull()})
it('빈 상태를 표시한다',()=>{render(<OwnerJobList storeName="매장" jobs={[]} onBack={vi.fn()} onSelect={vi.fn()}/>);expect(screen.getByRole('status')).toHaveTextContent('모집 중인 공고가 없어요.')})
it('마감 실패 시 목록을 바꾸지 않고 재시도 성공 시에만 갱신한다',async()=>{const close=vi.fn().mockRejectedValueOnce(Error('offline')).mockResolvedValue({...job,status:'closed'}),updated=vi.fn();render(<JobCloseFlow job={job} service={{close}} onClose={vi.fn()} onUpdated={updated}/>);fireEvent.click(screen.getByText('모집 마감'));await screen.findByRole('alert');expect(updated).not.toHaveBeenCalled();fireEvent.click(screen.getByText('모집 마감'));await screen.findByText('모집을 마감했어요');await act(async()=>{});expect(screen.getByText('공고 목록 보기')).toBeVisible();expect(updated).toHaveBeenCalledTimes(1)})
it('취소·중복 클릭·중단 후 응답을 안전하게 처리한다',async()=>{let resolve!:(v:OwnerJob)=>void;let signal!:AbortSignal;const close=vi.fn((_id,received:AbortSignal)=>{signal=received;return new Promise<OwnerJob>(done=>resolve=done)}),updated=vi.fn(),onClose=vi.fn();const view=render(<JobCloseFlow job={job} service={{close}} onClose={onClose} onUpdated={updated}/>);fireEvent.click(screen.getByText('모집 마감'));fireEvent.click(screen.getByText('모집 마감'));expect(close).toHaveBeenCalledTimes(1);fireEvent.click(screen.getByText('취소'));expect(signal.aborted).toBe(true);view.unmount();await act(async()=>resolve({...job,status:'closed'}));expect(updated).not.toHaveBeenCalled();expect(onClose).toHaveBeenCalledTimes(1)})
it('이미 마감된 공고의 중복 마감을 막는다',async()=>{const close=vi.fn(),onClose=vi.fn();render(<JobCloseFlow job={{...job,status:'closed'}} service={{close}} onClose={onClose} onUpdated={vi.fn()}/>);fireEvent.click(screen.getByText('모집 마감'));await waitFor(()=>expect(onClose).toHaveBeenCalled());expect(close).not.toHaveBeenCalled()})
