import {cleanup,fireEvent,render,screen,within} from '@testing-library/react'
import {afterEach,beforeEach,expect,it,vi} from 'vitest'
import {OwnerApplicants} from './OwnerApplicants'
import type {OwnerJob} from './model'
const job={id:'open',title:'오픈',storeName:'매장',date:'2026-09-27',start:'09:00',end:'14:00',nextDay:false,status:'recruiting'} as OwnerJob
const applicants=[{id:'park',name:'박지원',experience:'카페 근무 · 6개월',introduction:'음료 제조 경험이 있어요.\n안내대로 일하겠습니다.'},{id:'lee',name:'이민하',experience:'',introduction:'처음이지만 성실하게 일하겠습니다.'}]
beforeEach(()=>{Object.defineProperty(HTMLDialogElement.prototype,'showModal',{configurable:true,value:function(){this.setAttribute('open','')}});Object.defineProperty(HTMLDialogElement.prototype,'close',{configurable:true,value:function(){this.removeAttribute('open')}})})
afterEach(()=>{cleanup();Reflect.deleteProperty(HTMLDialogElement.prototype,'showModal');Reflect.deleteProperty(HTMLDialogElement.prototype,'close')})
it('원문을 읽기 전용으로 보여주고 닫으면 트리거에 포커스를 돌려준다',()=>{const request=vi.fn();render(<OwnerApplicants job={job} applicants={applicants} onBack={vi.fn()} onCloseJob={vi.fn()} onRequest={request}/>);const trigger=screen.getByRole('button',{name:'박지원 지원서 보기'});trigger.focus();fireEvent.click(trigger);const dialog=screen.getByRole('dialog');expect(within(dialog).getByText(/음료 제조 경험/).textContent).toBe(applicants[0].introduction);expect(within(dialog).queryByRole('textbox')).toBeNull();fireEvent.click(within(dialog).getByText('근무 요청 보내기'));expect(request).toHaveBeenCalledWith(applicants[0]);fireEvent.click(within(dialog).getByText('닫기'));expect(trigger).toHaveFocus();expect(screen.getByText('지원자 2명')).toBeVisible();expect(screen.getByText('등록한 경력 없음')).toBeVisible()})
it('빈 목록에서도 공고 정보와 마감 동작을 제공한다',()=>{const close=vi.fn();render(<OwnerApplicants job={job} applicants={[]} onBack={vi.fn()} onCloseJob={close} onRequest={vi.fn()}/>);expect(screen.getByText('지원자 0명')).toBeVisible();expect(screen.getByRole('status')).toHaveTextContent('아직 지원자가 없어요');fireEvent.click(screen.getByText('지원자 선정 없이 모집 마감'));expect(close).toHaveBeenCalledTimes(1)})
it.each([true,false])('열람 전용 또는 모집 종료 상태에서는 근무 요청을 제공하지 않는다 (%s)',readOnly=>{render(<OwnerApplicants job={readOnly?job:{...job,status:'closed'}} applicants={applicants} initialApplicantId="park" initialReadOnly={readOnly} onBack={vi.fn()} onCloseJob={vi.fn()} onRequest={vi.fn()}/>);expect(screen.queryByRole('button',{name:/근무 요청/})).toBeNull();if(!readOnly)expect(screen.getByRole('button',{name:'모집 종료'})).toBeDisabled()})
