import {act,cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react'
import {afterEach,beforeEach,expect,it,vi} from 'vitest'
import {WorkRequestFlow} from './WorkRequestFlow'
import type {OwnerJob} from './model'
const job={id:'open',title:'주말 오픈 대타',storeName:'매장',date:'2026-09-27',start:'09:00',end:'14:00',status:'recruiting'} as OwnerJob
const applicant={id:'park',name:'박지원',experience:'카페 근무 · 6개월',introduction:'자기소개'}
beforeEach(()=>{Object.defineProperty(HTMLDialogElement.prototype,'showModal',{configurable:true,value:function(){this.setAttribute('open','')}});Object.defineProperty(HTMLDialogElement.prototype,'close',{configurable:true,value:function(){this.removeAttribute('open')}})})
afterEach(()=>{cleanup();Reflect.deleteProperty(HTMLDialogElement.prototype,'showModal');Reflect.deleteProperty(HTMLDialogElement.prototype,'close')})
it('취소할 때 요청을 전송하지 않는다',()=>{const request=vi.fn(),close=vi.fn();render(<WorkRequestFlow job={job} applicant={applicant} service={{request}} onClose={close} onCompleted={vi.fn()}/>);expect(screen.getByText('박지원')).toBeVisible();fireEvent.click(screen.getByText('취소'));expect(close).toHaveBeenCalledOnce();expect(request).not.toHaveBeenCalled()})
it('정확한 공고와 지원자로 요청하고 완료 화면을 확인한 후에만 목록으로 돌아간다',async()=>{const request=vi.fn().mockResolvedValue(undefined),done=vi.fn(),close=vi.fn();render(<WorkRequestFlow job={job} applicant={applicant} service={{request}} onClose={close} onCompleted={done}/>);fireEvent.click(screen.getByText('요청하기'));await waitFor(()=>expect(screen.getByRole('dialog',{name:'요청을 완료했어요!'})).toBeVisible());expect(request).toHaveBeenCalledWith('open','park',expect.any(AbortSignal));expect(done).not.toHaveBeenCalled();expect(close).not.toHaveBeenCalled();fireEvent.click(screen.getByText('공고 목록 보기'));await act(async()=>{});expect(done).toHaveBeenCalledOnce()})
it('실패 시 성공 화면 없이 재시도하며 중복 전송을 막는다',async()=>{let resolve!:()=>void;const request=vi.fn().mockRejectedValueOnce(Error('FAIL')).mockImplementationOnce(()=>new Promise<void>(r=>{resolve=r}));render(<WorkRequestFlow job={job} applicant={applicant} service={{request}} onClose={vi.fn()} onCompleted={vi.fn()}/>);fireEvent.click(screen.getByText('요청하기'));expect(await screen.findByRole('alert')).toBeVisible();expect(screen.queryByText('요청을 완료했어요!')).toBeNull();fireEvent.click(screen.getByText('요청하기'));fireEvent.click(screen.getByText('요청하기'));expect(request).toHaveBeenCalledTimes(2);await act(async()=>{resolve()});await waitFor(()=>expect(screen.getByRole('dialog',{name:'요청을 완료했어요!'})).toBeVisible())})
it('닫은 요청은 취소하고 늦게 도착한 응답으로 완료 처리하지 않는다',async()=>{let resolve!:()=>void;let signal!:AbortSignal;const request=vi.fn((_job:string,_applicant:string,s:AbortSignal)=>{signal=s;return new Promise<void>(r=>{resolve=r})});const done=vi.fn(),close=vi.fn();const view=render(<WorkRequestFlow job={job} applicant={applicant} service={{request}} onClose={close} onCompleted={done}/>);fireEvent.click(screen.getByText('요청하기'));fireEvent.click(screen.getByText('취소'));expect(signal.aborted).toBe(true);expect(close).toHaveBeenCalledOnce();view.unmount();await act(async()=>{resolve()});expect(done).not.toHaveBeenCalled()})
it('종료한 공고의 요청을 거절한다',async()=>{const request=vi.fn();render(<WorkRequestFlow job={{...job,status:'closed'}} applicant={applicant} service={{request}} onClose={vi.fn()} onCompleted={vi.fn()}/>);fireEvent.click(screen.getByText('요청하기'));expect(await screen.findByRole('alert')).toBeVisible();expect(request).not.toHaveBeenCalled()})
it('서비스가 없으면 성공으로 간주하지 않는다',async()=>{render(<WorkRequestFlow job={job} applicant={applicant} onClose={vi.fn()} onCompleted={vi.fn()}/>);fireEvent.click(screen.getByText('요청하기'));expect(await screen.findByRole('alert')).toBeVisible();expect(screen.queryByText('요청을 완료했어요!')).toBeNull()})
