import { useState } from 'react'
import type { FormEvent } from 'react'
import { useApp, futureDate } from '../state'
import type { Applicant, Job } from '../state'
import { Badge, Button, Card, DetailRow, Empty, Field, Heading, Modal } from '../ui'

import { confirmApplicant, hasConflict, jobDateLabel, jobEnd, jobStart, matchesAvailability } from '../job-logic'
export function JobCard({ job }: { job: Job }) {
  const { data, go, now } = useApp(); const owner = data.role === 'owner'; const mine = job.applicants.find(app => app.email === data.profile.email && app.status !== 'withdrawn'); const count = job.applicants.filter(app => app.status === 'pending').length
  const badge = mine?.status === 'confirmed' ? '근무 확정' : mine ? '신청 완료' : job.status === 'closed' || jobStart(job) <= now ? '모집 마감' : owner ? count ? `지원자 ${count}명` : '지원자 없음' : '신청 가능'
  return <button className="list-button" onClick={() => go(`/jobs/${job.id}`)}><Card className="job-card"><div className="row between"><strong>{owner ? job.title : job.storeName}</strong><Badge tone={job.status === 'closed' && !mine || owner && !count ? 'gray' : 'blue'}>{badge}</Badge></div><p className="small muted">{!owner && `${job.category} ㅣ `}{jobDateLabel(job)}</p></Card></button>
}
function JobCreate() {
  const { data, update, go, notify } = useApp(); const [error, setError] = useState('')
  const [form, setForm] = useState({ title: '', task: '홀 서빙', date: futureDate(1), start: '09:00', end: '14:00', wage: '12000', capacity: '1', experience: '경력 무관', description: '' })
  const change = (key: keyof typeof form, value: string) => setForm(previous => ({ ...previous, [key]: value }))
  const submit = (event: FormEvent) => {
    event.preventDefault()
    if (!form.title.trim() || !form.date || !form.start || !form.end || new Date(`${form.date}T${form.start}`).getTime() <= Date.now()) return setError('제목과 미래의 근무 일시를 입력해 주세요.')
    if (form.start === form.end || !Number.isFinite(Number(form.wage)) || Number(form.wage) <= 0 || Number(form.capacity) < 1 || !Number.isInteger(Number(form.capacity))) return setError('근무 시간, 시급, 모집 인원을 확인해 주세요.')
    const job: Job = { id: `job-${crypto.randomUUID()}`, storeId: data.store.id, storeName: data.store.name, title: form.title.trim(), task: form.task, date: form.date, start: form.start, end: form.end, wage: Number(form.wage), capacity: Number(form.capacity), experience: form.experience, description: form.description.trim(), category: data.store.category, status: 'open', applicants: [] }
    update(previous => ({ ...previous, jobs: [job, ...previous.jobs] })); notify('공고를 등록했어요. 일반회원 화면에서 확인할 수 있어요.'); go(`/jobs/${job.id}`)
  }
  if (data.role !== 'owner' || data.store.status !== 'active') return <div className="page-content"><Empty title="매장 확인이 필요해요" description="운영 중인 매장의 점주만 공고를 등록할 수 있어요." /></div>
  return <form className="page-content stack" onSubmit={submit}><Heading title="함께할 근무자를 찾아요" description="업무와 근무 조건을 정확하게 알려 주세요." /><h2>기본 정보</h2><Field label="공고 제목" required value={form.title} maxLength={60} onChange={e => change('title', e.target.value)} placeholder="예: 주말 오픈 대타" /><label className="select-label">담당 업무<select value={form.task} onChange={e => change('task', e.target.value)}>{['홀 서빙', '매장 마감', '상품 입고·진열', 'POS 결제'].map(task => <option key={task}>{task}</option>)}</select></label><Field label="근무 매장" readOnly value={data.store.name} /><h2>근무 일시</h2><Field label="근무 날짜" type="date" required min={futureDate(0)} value={form.date} onChange={e => change('date', e.target.value)} /><div className="split-fields"><Field label="시작 시간" type="time" step="1800" required value={form.start} onChange={e => change('start', e.target.value)} /><Field label="종료 시간" type="time" step="1800" required value={form.end} onChange={e => change('end', e.target.value)} /></div>{form.end < form.start && <p className="small muted">종료 시각은 다음 날이에요.</p>}<h2>모집 조건</h2><div className="split-fields"><Field label="시급 (원)" type="number" min="1" step="100" required value={form.wage} onChange={e => change('wage', e.target.value)} /><Field label="모집 인원" type="number" min="1" max="20" required value={form.capacity} onChange={e => change('capacity', e.target.value)} /></div><label className="select-label">경험 조건<select value={form.experience} onChange={e => change('experience', e.target.value)}><option>경력 무관</option><option>관련 업무 경험자</option></select></label><label className="field">추가 안내<textarea value={form.description} onChange={e => change('description', e.target.value)} placeholder="담당 업무, 준비물, 휴게 시간 등을 알려 주세요." maxLength={1000} /></label><p className="notice">월계1동 공고로 등록돼요. 내부 매뉴얼은 근무가 확정된 사람에게만 제공돼요.</p>{error && <p className="form-error" role="alert">{error}</p>}<Button type="submit">공고 등록하기</Button></form>
}
function JobList() {
  const { data, go, now } = useApp(); const owner = data.role === 'owner'; const [query, setQuery] = useState(''); const [tab, setTab] = useState('전체'); const [newOnly, setNewOnly] = useState(false); const [availableOnly, setAvailableOnly] = useState(false); const [date, setDate] = useState('')
  const jobs = data.jobs.filter(job => (!owner || job.storeId === data.store.id) && `${job.title} ${job.storeName} ${job.task}`.includes(query) && (!date || job.date === date) && (!newOnly || job.experience === '경력 무관') && (!availableOnly || matchesAvailability(job, data.profile.availability)) && (tab === '전체' || tab === '모집 중' && job.status === 'open' && jobStart(job) > now || tab === '마감' && (job.status === 'closed' || jobStart(job) <= now) || tab === '내 신청' && job.applicants.some(app => app.email === data.profile.email && app.status !== 'withdrawn') || tab === '관심' && data.savedJobs.includes(job.id)))
  return <div className="page-content stack"><Heading title={owner ? '모집 공고를 관리해요' : '나에게 맞는 일을 찾아요'} description={owner ? '지원자를 확인하고 함께할 근무자를 선택하세요.' : '월계1동 매장의 대타 공고를 확인하세요.'} />{owner ? <Button onClick={() => go('/jobs/new')}>+ 공고 등록</Button> : <><Field label="공고 검색" value={query} onChange={e => setQuery(e.target.value)} placeholder="매장명 또는 업무를 검색해 보세요" /><div className="split-fields job-filters"><Field label="근무 날짜" type="date" value={date} onChange={e => setDate(e.target.value)} /><label className="check-label small"><input type="checkbox" checked={newOnly} onChange={e => setNewOnly(e.target.checked)} />경력 무관만 보기</label></div><label className="check-label small"><input type="checkbox" checked={availableOnly} onChange={e => setAvailableOnly(e.target.checked)} />내 가능 시간에 맞는 공고</label></>}<div className="chips" aria-label="공고 필터">{(owner ? ['전체', '모집 중', '마감'] : ['전체', '내 신청', '관심']).map(item => <button key={item} className={`chip ${tab === item ? 'active' : ''}`} aria-pressed={tab === item} onClick={() => setTab(item)}>{item}</button>)}</div><div className="row between"><h2>{tab === '전체' ? '공고 목록' : tab}</h2><span className="small muted">{jobs.length}건</span></div><div className="job-list">{jobs.map(job => <JobCard key={job.id} job={job} />)}{!jobs.length && <Empty title="조건에 맞는 공고가 없어요" description="검색어나 날짜를 바꾸어 다시 찾아보세요." />}</div></div>
}
function JobDetail({ id, applicantsView }: { id: string; applicantsView: boolean }) {
  const { data, update, go, notify, now } = useApp(); const [confirmation, setConfirmation] = useState<Applicant | null>(null); const [closeDialog, setCloseDialog] = useState(false); const [withdraw, setWithdraw] = useState(false); const [error, setError] = useState('')
  const job = data.jobs.find(item => item.id === id); const owner = data.role === 'owner'; if (!job) return <div className="page-content"><Empty title="공고를 찾을 수 없어요" /><Button onClick={() => go('/jobs')}>공고 목록으로</Button></div>
  const mine = job.applicants.find(app => app.email === data.profile.email && app.status !== 'withdrawn'); const expired = jobStart(job) <= now; const pending = job.applicants.filter(app => app.status !== 'withdrawn')
  const apply = () => {
    const current = data.jobs.find(item => item.id === job.id)
    if (!current || data.role !== 'member' || data.store.status !== 'active' || current.status !== 'open' || jobStart(current) <= Date.now() || current.applicants.some(app => app.email === data.profile.email && app.status !== 'withdrawn')) return setError('신청할 수 없는 공고예요. 모집 상태와 근무 일시를 확인해 주세요.')
    if (hasConflict(data.jobs, current, data.profile.email)) return setError('이미 확정된 근무와 시간이 겹쳐 신청할 수 없어요.')
    if (current.experience !== '경력 무관' && (data.profile.experience !== 'experienced' || !data.profile.careers.some(career => career.task === current.task))) return setError('이 공고는 관련 업무 경험이 필요해요. 프로필의 근무 정보를 확인해 주세요.')
    const applicant: Applicant = { id: `app-${crypto.randomUUID()}`, name: data.profile.name, email: data.profile.email, experience: data.profile.experience === 'new' ? '신입' : data.profile.careers.map(c => `${c.industry} · ${c.task}`).join(', '), status: 'pending' }
    update(previous => {
      const latest = previous.jobs.find(item => item.id === job.id)
      if (!latest || previous.role !== 'member' || previous.store.status !== 'active' || latest.status !== 'open' || jobStart(latest) <= Date.now() || latest.applicants.some(app => app.email === previous.profile.email && app.status !== 'withdrawn') || hasConflict(previous.jobs, latest, previous.profile.email)) return previous
      return { ...previous, readNotifications: false, jobs: previous.jobs.map(item => item.id === latest.id ? { ...item, applicants: [...item.applicants, applicant] } : item) }
    }); notify('신청을 완료했어요. 점주의 근무 확정을 기다려 주세요.')
  }
  const confirm = () => { if (!confirmation) return; const result = confirmApplicant(data, job.id, confirmation.id); if (result.error) setError(result.error); else { update(() => result.data); notify(`${confirmation.name}님의 근무를 확정했어요. 온보딩 자료를 바로 확인할 수 있어요.`) } setConfirmation(null) }
  return <div className="page-content stack"><div className="row between"><Badge tone={job.status === 'open' && !expired ? 'blue' : 'gray'}>{job.status === 'open' && !expired ? '모집 중' : '모집 마감'}</Badge><span className="small muted">월계1동</span></div><Heading title={applicantsView ? '함께할 근무자를 선택해요' : job.title} description={job.storeName} />{!applicantsView && <><Card className="stack"><h2>근무 일정</h2><DetailRow label="날짜">{job.date.replaceAll('-', '. ')}</DetailRow><DetailRow label="근무 시간">{job.start}–{job.end}{job.end <= job.start ? ' (다음 날)' : ''}</DetailRow><DetailRow label="모집 인원">{job.capacity}명</DetailRow></Card><Card className="stack"><h2>보수 및 업무 조건</h2><DetailRow label="시급"><strong className="primary-text">{job.wage.toLocaleString()}원</strong></DetailRow><DetailRow label="담당 업무">{job.task}</DetailRow><DetailRow label="경험 요건">{job.experience}</DetailRow><p className="muted">{job.description || '추가 안내가 없어요. 담당 업무를 확인해 주세요.'}</p></Card><Card className="stack"><h2>매장 정보</h2><p>{job.storeName}</p><p className="small muted">{data.store.address}</p></Card></>}
    {owner ? <><div className="row between"><h2>지원자 목록</h2><Badge>{pending.length}명</Badge></div>{!pending.length && <Empty title="아직 지원자가 없어요" description="일반회원 화면에서 공고에 신청해 볼 수 있어요." />}{pending.map(applicant => <Card className="stack" key={applicant.id}><div className="row between"><h3>{applicant.name}</h3><Badge tone={applicant.status === 'confirmed' ? 'green' : 'blue'}>{applicant.status === 'confirmed' ? '근무 확정' : '신청 완료'}</Badge></div><p className="small muted">{applicant.experience || '등록한 업무 경험이 없어요.'}</p>{applicant.status === 'pending' && <Button disabled={job.status === 'closed' || expired} onClick={() => setConfirmation(applicant)}>근무 확정하기</Button>}</Card>)}{job.status === 'open' && !expired && <Button variant="secondary" onClick={() => setCloseDialog(true)}>모집 마감하기</Button>}</> : <><p className="notice">신청만으로 근무가 확정되지 않아요. 점주가 확정하면 담당 업무의 매뉴얼을 확인할 수 있어요.</p>{mine?.status === 'confirmed' ? <><Card className="stack"><Badge tone="green">근무 확정</Badge><h2>함께하게 되어 반가워요!</h2><p className="muted">{jobEnd(job) > now ? '첫 출근 전, 담당 업무를 미리 확인해 보세요.' : '근무가 종료되어 이 공고의 자료 접근 기간이 끝났어요.'}</p></Card><Button disabled={jobEnd(job) <= now} onClick={() => go('/manuals')}>온보딩 시작하기</Button></> : mine ? <><Badge>신청 완료 · 확정 대기</Badge><Button variant="secondary" disabled={expired} onClick={() => setWithdraw(true)}>신청 철회하기</Button></> : <Button disabled={job.status !== 'open' || expired} onClick={apply}>{job.status !== 'open' || expired ? '모집이 마감되었어요' : '이 공고에 신청하기'}</Button>}<Button variant="ghost" onClick={() => update(previous => ({ ...previous, savedJobs: previous.savedJobs.includes(job.id) ? previous.savedJobs.filter(id => id !== job.id) : [...previous.savedJobs, job.id] }))}>{data.savedJobs.includes(job.id) ? '♥ 관심 공고에서 삭제' : '♡ 관심 공고에 저장'}</Button></>}
    {error && <p className="form-error" role="alert">{error}</p>}
    {confirmation && <Modal title="근무를 확정할까요?" onClose={() => setConfirmation(null)}><p>{confirmation.name}님에게 {job.task} 온보딩 자료가 제공돼요. 접근은 근무 종료 시 만료돼요.</p><Button onClick={confirm}>확정하기</Button><Button variant="secondary" onClick={() => setConfirmation(null)}>돌아가기</Button></Modal>}
    {closeDialog && <Modal title="모집을 마감할까요?" onClose={() => setCloseDialog(false)}><p>마감 후에는 추가 신청과 지원자 확정을 할 수 없어요.</p><Button onClick={() => { update(previous => ({ ...previous, jobs: previous.jobs.map(item => item.id === job.id ? { ...item, status: 'closed' } : item) })); setCloseDialog(false); notify('모집을 마감했어요.') }}>마감하기</Button><Button variant="secondary" onClick={() => setCloseDialog(false)}>돌아가기</Button></Modal>}
    {withdraw && <Modal title="신청을 철회할까요?" onClose={() => setWithdraw(false)}><p>공고가 모집 중인 동안에는 다시 신청할 수 있어요.</p><Button variant="danger" onClick={() => { update(previous => ({ ...previous, jobs: previous.jobs.map(item => item.id === job.id ? { ...item, applicants: item.applicants.map(app => app.id === mine?.id ? { ...app, status: 'withdrawn' } : app) } : item) })); setWithdraw(false); notify('신청을 철회했어요.') }}>철회하기</Button><Button variant="secondary" onClick={() => setWithdraw(false)}>돌아가기</Button></Modal>}
  </div>
}
export function JobPages({ route }: { route: string }) { if (route === '/jobs/new') return <JobCreate />; if (route === '/jobs') return <JobList />; return <JobDetail id={route.split('/')[2]} applicantsView={route.endsWith('/applicants')} /> }
